### ISSUE TITLE
Produce a script to flatten-out metadata.yml into a csv

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/object-store-harvestor#60]
**NOTE**: this is _not_ a new requirement for the object-store-harvestor, but an independent request for a new, one-off post-processing script.

Given a parent directory within which are many nested child directories on the Biocluster, loop through all of them, find all metadata.yml documents, read them and flatten-out their contents into a single csv file with the exception of the OCR managed attribute. In this case, the directory on the isilon will be /isilon/ottawa-rdc-htds.

metadata.yml
```
---
# Use UUID for Heather Cole
acMetadataCreator: d3681c90-80a3-43b7-8471-23ef718c3967
# Use UUID for Heather Cole
dcCreator: d3681c90-80a3-43b7-8471-23ef718c3967
original: Image001.cr2
uploadWithFilename: "01-01460745.cr2"
orientation: 8
derivative: Preview001.jpg
managedAttributes:
  # originalDirectoryName
  original_directory_name: "dc1.2019-11-06_08-58-27_09a8ac"
  # folderBarcode
  folder_barcode: "F-015359"
  # barcode
  barcode: "01-01460745"
  # catalogNumber
  catalog_number:
  # country
  country: Canada
  # stateProvince
  state_province: "British Columbia"
  # folderColour
  folder_colour: beige
  # filedAsName
  filed_as_name: Viburnum edule
  # ocr
  ocr: > stuff here
```

Expected output:

| acMetadataCreator                    | dcCreator                            | original     | uploadWithFilename | orientation | derivative     | original_directory_name        | folder_barcode | barcode     | catalog_number | country | state_province   | folder_colour | filed_as_name  |
|--------------------------------------|--------------------------------------|--------------|--------------------|-------------|----------------|--------------------------------|----------------|-------------|----------------|---------|------------------|---------------|----------------|
| d3681c90-80a3-43b7-8471-23ef718c3967 | d3681c90-80a3-43b7-8471-23ef718c3967 | Image001.cr2 | 01-01460745.cr2    | 8           | Preview001.jpg | dc1.2019-11-06_08-58-27_09a8ac | F-015359       | 01-01460745 |                | Canada  | British Columbia | beige         | Viburnum edule |
| etc. for all other metadata.yml files                                 |                                      |              |                    |             |                |                                |                |             |                |         |                  |               |                |
|                                      |                                      |              |                    |             |                |                                |                |             |                |         |                  |               |                |
